### ISSUE TITLE
Next.js: Warning `prop` className did not match. Server: "generated_server_className" Client: "generated_client_className"

### ISSUE THREAD

**Issue by jaycedotbin** [seek-oss/vanilla-extract#369]
### Describe the bug

After next.js compiles it throws a runtime error with something along the lines of:
```javascript
Warning: Prop `className` did not match. Server: "pages_themeClass__sryalf0" Client: "pages__createTheme__sryalf0"
```

### Link to reproduction

I have a fork of next.js that has an example of vanilla-extract with [typescript](https://github.com/jaycedotbin/next.js/tree/canary/examples/with-vanilla-extract-typescript) and [javascript](https://github.com/jaycedotbin/next.js/tree/canary/examples/with-vanilla-extract-javascript)

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.14 Arch Linux
    CPU: (4) x64 AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G
    Memory: 341.82 MB / 6.74 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.local/share/volta/tools/image/node/14.17.6/bin/node
    npm: 6.14.15 - ~/.local/share/volta/tools/image/node/14.17.6/bin/npm
  Browsers:
    Brave Browser: 93.1.29.81
  npmPackages:
    @vanilla-extract/css: ^1.6.0 => 1.6.0
```

**Comment by BarnabyBishop** [comment]
I've been looking into this one as I had the same issue when adding vanilla-extract to an existing NextJS site. 

**The issue**
`createTheme` can cause an issue in NextJS sites running in dev mode as the className generated on the server does not match the one generated on the client. This doesn't appear to be an issue when the site is built and running in production mode. 

**Example**
I created a reproducible example with a basic create-next-app typescript app with a basic vanilla-extract implementation:
https://github.com/BarnabyBishop/nextjs-vanilla-extract

**Potential workaround**
I was able to fix the issue in the above repo by adding a browserlist in the `package.json`:
```"browserslist": [
    ">0.3%",
    "not ie 11"
  ]```

You can see an example on the `working` branch of the above repo: https://github.com/BarnabyBishop/nextjs-vanilla-extract/blob/working/package.json#L25

However adding this to the original app I'm working on hasn't solved the issue. Still looking into what's going on there.

**Comment by markdalgleish** [comment]
I believe this is caused by differing Babel targets between the client and server builds which means that the vanilla-extract Babel plugin can't consistently create debug IDs for you.

As a workaround, you can apply an explicit debug ID yourself:

```diff
-export const [themeClass, vars] = createTheme({ ...tokens ]);
+export const [themeClass, vars] = createTheme({ ...tokens ], 'myDebugId');
```

**Comment by markdalgleish** [comment]
This is now fixed in `@vanilla-extract/babel-plugin@1.1.1`.

**Comment by BarnabyBishop** [comment]
Legend! Thanks @markdalgleish

**Comment by jaycedotbin** [comment]
Than you ! @markdalgleish

**Comment by sami616** [comment]
@markdalgleish  this one appears to have worked its way back in somehow? using the workaround of adding an explicit debug id has fixed this as a workaround.

    "@vanilla-extract/css": "^1.9.5",
    "@vanilla-extract/next-plugin": "2.0.1",

**Comment by lamualfa** [comment]
Still doesn't work with `@vanilla-extract/next-plugin@^2.1.3`.
